Generalize data insertion capacity in orderbook
IteraLabs/atelier pull request #16
Opened 2024-08-26 15:21 UTC by IFFranciscoME

quick fix to extend the functionality of the Orderbook struct:

[DONE]
1. Added a `volume` field in the `Level` type which is used in the bids: `Vec<Level>`, `asks: Vec<Level>` within the `Orderbook` type. With this, now there is the optionality of either providing order-level granularity, or, just price and volume granularity, when creating a Level. And so to keep supporting the two types of filling processes:

- For the Synthetic Data Generation: The `volume` field in the `Level` type, now is the sum of the generated vector of `Order` types. 
- For the Market Data Insertion: The `volume` field is one field within the `Level` type that is needed to be included.

[WIP]

2. Created the `insert` method for the `Orderbook` type.

Insertion into the `Orderbook` corresponding fields `bids` and `asks` now can be done by providing a collection of `Level`-like compatible types, including an internal validation of this. 

For this PR only one case is implemented, a struct with named and typed fields that mimic 1:1 of those of the `Level` internal type at `atelier::data::market::Level` 

[DONE]

3. Introduced some formatting changes.

In this PR there are changes given a few slight modifications on the rust formatting options within the added file `rustfmt.toml`

2024-08-31 16:27 UTC, CAGS295 requested changes
I need a method Level::from_update(&mut self, price: f64, volume: f64) to insert updates from an order_book update.

2024-08-31 16:27 UTC, CAGS295 commented on tests/orderbook_static.rs
> +#[warn(dead_code)]
?

2024-08-31 16:27 UTC, CAGS295 commented on tests/orderbook_static.rs
> +    fn orderbook_insert_levels() {
Does not test insertion.

2024-08-31 16:27 UTC, CAGS295 commented on rustfmt.toml
> +max_width = 80
unrealted

2024-08-31 16:27 UTC, CAGS295 commented on tests/orderbook_static.rs
This is not an integration test. unit tests don't go in this folder.

2024-08-31 16:27 UTC, CAGS295 commented on src/data/market.rs
> +    pub fn insert(mut self, level_data: Level) {
No insertion checks in neither the insert and constructor, Level can be whatever. I can't construct a Level from an orderbook update, a price and volume level don't make a Level.

2024-09-03 02:12 UTC, IFFranciscoME commented on tests/orderbook_static.rs
> +#[warn(dead_code)]
Consider add more explicit content to avoid ambiguity, as well as to include references to either existing issues, PRs or code artifacts. 

This file was affected by the #21, consider revisit that version of the project

2024-09-03 02:12 UTC, IFFranciscoME commented on rustfmt.toml
> +max_width = 80
This file was affected by the #21, consider revisit that version of the project

2024-09-03 02:29 UTC, IFFranciscoME commented on tests/orderbook_static.rs
This was resolved in the most recent PR #21

2024-09-16 05:25 UTC, CAGS295 commented
- Insertion methods for bids and asks.
Due to current dependency limitations, you will have to install protoc. I hope to lift this requirement soon.

2024-09-16 05:38 UTC, CAGS295 approved these changes

2024-09-29 23:31 UTC, closed without merging

2024-09-29 23:31 UTC, CAGS295 commented
Closing in favor of #33