Synthetic Orderbook naive creation
IteraLabs/atelier pull request #5
Opened 2024-08-17 17:51 UTC by IFFranciscoME

A synthetic orderbook creation is a process that generates from purely random, or non-regressive way, the necessary data for an Orderbook to exist. That is, sides, levels and orders with price, volume and timestamp. 

basic usage is:

```rust
fn main() {
  
  let bid_price = 50_000.00;
  let ask_price = 50_100.00;
  let tick_size = 100.0;
  let n_levels = 200;
  let n_orders = 300;
  
  let i_ob = Orderbook::synthetize(bid_price, ask_price, tick_size, n_levels, n_orders);
  
  println!("\nlevel_id {:?}", i_ob.bids[199].level_id);
  println!("side {:?}", i_ob.bids[199].side);
  println!("price {:?}", i_ob.bids[199].price);
  println!("orders[0]{:?}", i_ob.bids[199].orders[0]);
  println!("orders[1]{:?}", i_ob.bids[199].orders[1]);
}
```

And modified files where mainly the following: 

- the ones in the mod structs/marketdata/

2024-08-17 18:10 UTC, CAGS295 requested changes

2024-08-17 18:10 UTC, CAGS295 commented on rust/simulation/randomizer.rs
> +    // println!("now_ts: {:?}", now_ts);
a lot of dead code, consider using a logger

2024-08-17 18:10 UTC, CAGS295 commented on rust/simulation/randomizer.rs
> +pub fn randomize_order(side: String, price: f64) -> Order {
Don take side as string, use an enum

2024-08-17 18:10 UTC, CAGS295 commented on rust/structs/marketdata/orderbook.rs
>      pub orderbook_ts: f64,
floats has relative error, it's a good practice to use integers for timestamps.

2024-08-17 18:10 UTC, CAGS295 commented on rust/structs/marketdata/orderbook.rs
> +            v_bid_orders.sort_by_key(|order| order.order_ts);
Consider generating ts monotonically increasing to eliminate the sorting step.

2024-08-17 18:10 UTC, CAGS295 commented on rust/structs/marketdata/orderbook.rs
> +        let mut i_asks = Vec::new();
if you know the size a priori, instantiate with capacity to avoid mem realloc.

2024-08-20 17:52 UTC, IFFranciscoME commented on rust/main.rs
I think this is a good idea, and one good reason to reestructure the project to be a `lib` first, not a binary. And, for practical usability showcase, the `examples/` should do the job, which for the beta development phase can be considered as a lightweight replacement for the `main.rs`. 

I'll take this as part of a new Issue, which will contain the inclusion of the `examples/` folder, but also the refactoring to rust-only code for now, and, a `library layout` so will be dropping the `main.rs` and the `cargo.toml` details for this.

2024-08-20 17:53 UTC, IFFranciscoME commented on rust/simulation/randomizer.rs
> +    // println!("now_ts: {:?}", now_ts);
Good point, will add another ticket for the logging component in general.

2024-08-20 17:59 UTC, IFFranciscoME commented on rust/structs/marketdata/orderbook.rs
> +            v_bid_orders.sort_by_key(|order| order.order_ts);
This is true in the computational sense, but in the business use case the generated timestamps is part of the simulation of the stochastic nature of the expected time of arrival for an order. So the naive version of generating equally spaced-in-time order timestamps is not necessarily for now (maybe not at all), but certainly not worthy to refactor this for now. 

One thing that will be interesting is to generate always equal or greater timestamps, and to do so one by one. Maybe this requirement for enhancement could include the P.D.F. generators to draw samples from parametric distributions.

2024-08-20 18:01 UTC, IFFranciscoME commented on rust/structs/marketdata/orderbook.rs
> +        let mut i_asks = Vec::new();
There will be cases where the capacity of the Orderbook is fixed, e.g. 100 levels max for each side, and, 500 orders max per level for all levels. Definitely a good opportunity for computational resources optimization. This can be taken as a reference for another issue later on, as an enhancement.

2024-08-20 18:27 UTC, IFFranciscoME commented on rust/main.rs
I'll merge first this branch, and then on top of updated main with this, start the branch created that is referring to this comment.

2024-08-20 18:27 UTC, IFFranciscoME commented on rust/simulation/randomizer.rs
> +    // println!("now_ts: {:?}", now_ts);
Track this: https://github.com/IteraLabs/atelier/issues/7 for logging related updates

2024-08-20 18:29 UTC, IFFranciscoME commented on rust/simulation/randomizer.rs
> +pub fn randomize_order(side: String, price: f64) -> Order {
This can be considered as an enhancement of the overall data structures proposition, will be addressed properly in a new issue later on.

2024-08-20 18:29 UTC, IFFranciscoME commented on rust/structs/marketdata/orderbook.rs
>      pub orderbook_ts: f64,
This can be considered as an enhancement of the overall data structures proposition, will be addressed properly in a new issue later on.

2024-08-20 18:33 UTC, IFFranciscoME commented
Addressed comments and created subsequent issues and tickets. Ready to merge

2024-08-20 18:33 UTC, merged